export const tweetsData = [
  {
    handle: `@WildeInWestminster`,
    profilePic: `assets/wilde.jpg`,
    likes: 1847,
    reposts: 423,
    tweetText: `The birds are singing their usual morning symphony. How delightfully tedious. One does wonder if they ever tire of their own voice.`,
    replies: [
      {
        handle: `@DeafComposer1770`,
        profilePic: `assets/beethoven.jpg`,
        tweetText: `WHAT ARE THEY SINGING?? I'M DEAF. Can someone PLEASE describe the birdsong to me in EXCRUCIATING DETAIL???`,
      },
      {
        handle: `@WildeInWestminster`,
        profilePic: `assets/wilde.jpg`,
        tweetText: `My dear Ludwig, imagine the sound of someone relentlessly cheerful at 6am. That is birdsong.`,
      },
      {
        handle: `@ChildProdigyVibes`,
        profilePic: `assets/mozart.jpg`,
        tweetText: `@DeafComposer1770 It goes like: tweet tweet chirp chirp TWEET. You're welcome 🎵`,
      },
    ],
    isLiked: false,
    isReposted: false,
    uuid: "4b161eee-c0f5-4545-9c4b-8562944223ee",
  },
  {
    handle: `@TheBardsThe1Thing`,
    profilePic: `assets/shakespeare.jpg`,
    likes: 2847,
    reposts: 892,
    tweetText: `To tweet or not to tweet, that is the question. Whether 'tis nobler to share one's thoughts or keep them to oneself...`,
    replies: [
      {
        handle: `@SixWordStories`,
        profilePic: `assets/hemingway.jpg`,
        tweetText: `Just tweet, Bill. Stop overthinking it.`,
      },
    ],
    isLiked: false,
    isReposted: false,
    uuid: "3c23454ee-c0f5-9g9g-9c4b-77835tgs2",
  },
  {
    handle: `@RadioactiveMarie`,
    profilePic: `assets/curie.jpg`,
    likes: 5403,
    reposts: 1284,
    tweetText: `Just discovered a new element! Glowing with excitement. Literally. Should probably see a doctor.`,
    replies: [],
    isLiked: false,
    isReposted: false,
    uuid: "8hy671sff-c0f5-4545-9c4b-1237gyys45",
  },
  {
    handle: `@NotThatShort`,
    profilePic: `assets/napoleon.jpg`,
    likes: 394,
    reposts: 67,
    tweetText: `People keep making jokes about my height. I conquered most of Europe but sure, let's focus on that. 🙄`,
    replies: [
      {
        handle: `@HistoryNerd1815`,
        profilePic: `assets/tall.jpg`,
        tweetText: `Mate, you were literally average height for the time period`,
      },
      {
        handle: `@NotThatShort`,
        profilePic: `assets/napoleon.jpg`,
        tweetText: `THANK YOU. British propaganda is still ruining my reputation 200 years later`,
      },
    ],
    isLiked: false,
    isReposted: false,
    uuid: "7js83jss-c0f5-4545-9c4b-8395kd83js",
  },
  {
    handle: `@Vincent`,
    profilePic: `assets/vangogh.jpg`,
    likes: 891,
    reposts: 234,
    tweetText: `Painted another starry night. Feeling underappreciated. Again. Maybe I should try abstract art?`,
    replies: [],
    isLiked: false,
    isReposted: false,
    uuid: "9dj49dks-c0f5-4545-9c4b-9348fjsd73",
  },
];
